spring:
  application:
    name: RajaLib
  datasource:
    url: jdbc:mysql://localhost:3306/rajalib?serverTimezone=UTC
    username: sandesh
    password: cihaEGM*U46lrC$@3
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true


server:
  port: 8010

logging:
  level:
    org:
      hibernate:
        bytecode: ERROR