spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rajalib?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10 # Minimum number of idle connections in the pool
      maximum-pool-size: 50 # Maximum number of connections in the pool
      idle-timeout: 600000 # Maximum time that a connection is allowed to sit idle in the pool (10 minutes)
      max-lifetime: 1800000 # Maximum lifetime of a connection in the pool (30 minutes)
      connection-timeout: 30000 # Maximum time to wait for a connection from the pool (30 seconds)
      pool-name: HikariPool-1 # Name of the pool

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl   
      ddl-auto: none
    show-sql: true

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        bytecode: ERROR
