server:
  port : 8080

spring:
    application:
      name: "RajaLib"
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jspspringboot
      username: root
      password: root
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: true       
      hibernate:
        ddl-auto: update
      generate-ddl: true
    mvc:
      view: 
        prefix: /
        suffix: .jsp
    messages:
      basename: validation

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 
      refresh-token:
        expiration: 604800000 
        
logging:
  level:
    root: INFO
    org.springframework.web: ERROR 